pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'golang:1.21'
                    args '-u root'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh '''
                        mkdir -p /.cache/go-build
                        go install github.com/jstemmer/go-junit-report@latest
                        go clean -testcache
                        go test -v -coverprofile=coverage.out ./... 2>&1 | go-junit-report > report.xml
                        go tool cover -html=coverage.out -o coverage.html
                        mkdir -p reports
                        mv coverage.html reports/
                    '''
                }
            }
            post {
                always {
                    junit 'bugtracker-backend/report.xml'
                    publishHTML target: [
                      reportDir: 'bugtracker-backend/reports',
                      reportFiles: 'coverage.html',
                      reportName: 'Backend Coverage Report'
                    ]
                }
            }
        }

        stage('Unit Tests - Frontend') {
            agent {
                docker {
                    image 'node:20-alpine'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-frontend') {
                    sh '''
                        npm ci
                        npm test -- --coverage
                    '''
                }
            }
            post {
                always {
                    junit 'bugtracker-frontend/test-results.xml'
                    publishHTML target: [
                      reportDir: 'bugtracker-frontend/coverage',
                      reportFiles: 'index.html',
                      reportName: 'Frontend Coverage Report'
                    ]
                }
            }
        }
    }
}
