pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    args '-u root'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend') {
                  sh '''
                        mkdir -p /.cache/go-build
                        go clean -testcache
                        go test -v ./... 2>&1 | go-junit-report > report.xml
                    '''
                    # Genereate coverage report

                }
            }
            post {
                always {
                    junit 'bugtracker-backend/report.xml'
                }
            }
        }

        stage('Unit Tests - Frontend') {
            agent {
                docker {
                    image 'node:20-alpine'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-frontend') {
                    sh '''
                        npm ci
                        npm test
                        mkdir -p reports
                        mv coverage reports/
                    '''
                }
            }
            post {
                always {
                    junit 'bugtracker-frontend/test-results.xml'
                    publishHTML target: [
                      reportDir: 'bugtracker-frontend/reports/coverage',
                      reportFiles: 'index.html',
                      reportName: 'Frontend Coverage Report'
                    ]
                }
            }
        }
    }
}
